import Link from "next/link";
import { DashboardTopBar } from "@/components/dashboard/DashboardTopBar";
import { listCorrections } from "@/lib/corrections/data";
import { CORRECTION_REASON_TYPES, CORRECTION_STATUSES } from "@/lib/corrections/types";

interface PageProps { searchParams: Promise<{ date?: string; worker?: string; status?: string; reason?: string }> }
function money(value: number): string { return value.toLocaleString("th-TH", { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }
const statusLabel: Record<string, string> = { pending: "รออนุมัติ", approved: "อนุมัติแล้ว", rejected: "ปฏิเสธ", superseded: "ถูกแทนที่", cancelled: "ยกเลิก" };

export default async function CorrectionsPage({ searchParams }: PageProps) {
  const params = await searchParams;
  const rows = await listCorrections(params);
  return <><DashboardTopBar title="รายการปรับแก้" /><main className="space-y-4 p-4 sm:p-6"><form className="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-5"><input name="date" type="date" defaultValue={params.date} className="h-10 rounded-lg border border-slate-300 px-3" /><input name="worker" placeholder="พนักงาน/ตลาด" defaultValue={params.worker} className="h-10 rounded-lg border border-slate-300 px-3" /><select name="status" defaultValue={params.status} className="h-10 rounded-lg border border-slate-300 bg-white px-3"><option value="">ทุกสถานะ</option>{CORRECTION_STATUSES.map((value) => <option key={value} value={value}>{statusLabel[value]}</option>)}</select><select name="reason" defaultValue={params.reason} className="h-10 rounded-lg border border-slate-300 bg-white px-3"><option value="">ทุกเหตุผล</option>{CORRECTION_REASON_TYPES.map((value) => <option key={value}>{value}</option>)}</select><button className="h-10 rounded-lg bg-slate-800 px-4 text-sm font-semibold text-white">กรองรายการ</button></form><div className="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-240 text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr>{['วันที่/ผู้ขาย', 'รายการ', 'ค่าเดิม → ค่าใหม่', 'ผลกระทบ', 'เหตุผล', 'สถานะ', 'ผู้แจ้ง/ผู้อนุมัติ'].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t border-slate-100 hover:bg-slate-50"><td className="px-4 py-3">{row.before_snapshot.transactionDate}<div className="text-xs text-slate-400">{row.before_snapshot.staffName} · {row.before_snapshot.marketName}</div></td><td className="px-4 py-3"><Link href={`/corrections/${row.id}`} className="font-semibold text-slate-900 hover:text-emerald-700">{row.after_snapshot.productName}</Link><div className="text-xs text-slate-400">{row.before_snapshot.transactionType}</div></td><td className="px-4 py-3 tabular-nums">{money(row.before_snapshot.totalAmount)} → {money(row.after_snapshot.totalAmount)}</td><td className="px-4 py-3 font-semibold tabular-nums">{money(row.after_snapshot.totalAmount - row.before_snapshot.totalAmount)}</td><td className="px-4 py-3">{row.reason_type}<div className="max-w-50 truncate text-xs text-slate-400">{row.reason_detail}</div></td><td className="px-4 py-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-medium">{statusLabel[row.status]}</span></td><td className="px-4 py-3 font-mono text-xs">{row.requested_by.slice(0, 8)}<div className="text-slate-400">{row.approved_by?.slice(0, 8) ?? '—'}</div></td></tr>)}{rows.length === 0 && <tr><td colSpan={7} className="p-12 text-center text-slate-500">ไม่พบรายการแก้ไข</td></tr>}</tbody></table></div></main></>;
}
